import {
  Utensils,
  CakeSlice,
  CupSoda,
  Smartphone,
  CarFront,
  CircleUserRound,
  House,
  Shirt,
  HousePlus,
  SmilePlus,
  HeartPulse,
  GraduationCap,
  CircleQuestionMark,
  Wallet,
  PiggyBank,
  Gift,
  ChartPie,
  Bitcoin,
  HandCoins,
  // Additional icons from CUCategoryModal
  Coffee,
  Pizza,
  Apple,
  Cake,
  GlassWater,
  Car,
  Bus,
  Plane,
  Train,
  Bike,
  Fuel,
  ShoppingBag,
  ShoppingCart,
  Sparkles,
  Home,
  Flame,
  Droplet,
  Bolt,
  Wifi,
  DollarSign,
  TrendingUp,
  Coins,
  Briefcase,
  Dumbbell,
  Pill,
  Stethoscope,
  Gamepad2,
  Film,
  Music,
  BookOpen,
  Tv,
  Baby,
  Users,
  Heart,
  Wrench,
  Settings,
  Phone,
  Shield,
  FileText,
  Mail,
  // New additional icons requested
  CreditCard,
  Receipt,
  Store,
  Ticket,
  Wine,
  Hotel,
  MapPin,
  Dog,
  Cat,
  Hammer,
  Scissors,
  Key,
  Trash2,
  Sun,
  Umbrella,
  Activity,
  Brain,
  Bed,
  Crown,
  Trophy,
  Award,
  HeartHandshake,
  Calculator,
  // Newly added icons for expanded selection
  Soup,
  Beer,
  IceCream,
  Fish,
  Egg,
  Croissant,
  Popcorn,
  Cookie,
  Map,
  Globe,
  Compass,
  Landmark,
  Luggage,
  Tent,
  Mountain,
  Anchor,
  Ship,
  Sofa,
  Lightbulb,
  Plug,
  Bath,
  Brush,
  Laptop,
  Tablet,
  Mouse,
  Printer,
  Banknote,
  Percent,
  CirclePercent,
  Presentation,
  ShieldCheck,
  Hospital,
  Ambulance,
  Footprints,
  Eye,
  Syringe,
  Book,
  Bookmark,
  PenTool,
  Palette,
  Mic,
  Headphones,
  Camera,
  Clapperboard,
  Target,
  PawPrint,
  TreePine,
  Flower2,
  Leaf,
  Bell,
  Calendar,
  Clock,
  Star,
  Cloud,
  Moon,
  LucideIcon,
} from "lucide-react";

// Mapping for legacy system categories (Expenses)
// Exactly matching values in apps/api/src/common/constants/default-categories.ts
export const iconMappingExpense: Record<string, LucideIcon> = {
  food: Utensils,
  snack: CakeSlice,
  drink: CupSoda,
  phone: Smartphone,
  transport: CarFront,
  personal: CircleUserRound,
  home: House,
  laundry: Shirt,
  household: HousePlus,
  cosmetic: SmilePlus,
  medical: HeartPulse,
  education: GraduationCap,
  other: CircleQuestionMark,
};

// Mapping for legacy system categories (Income)
// Exactly matching values in apps/api/src/common/constants/default-categories.ts
export const iconMappingIncome: Record<string, LucideIcon> = {
  salary: Wallet,
  wallet: PiggyBank,
  bonus: Gift,
  freelance: ChartPie,
  investment: Bitcoin,
  other: HandCoins,
  personal: CircleQuestionMark,
};

// List of all selectable icons for CUCategoryModal display
export const SELECTABLE_ICONS = [
  // Default system categories icons (Legacy names matching apps/api/src/common/constants/default-categories.ts)
  "food",
  "snack",
  "drink",
  "phone",
  "transport",
  "personal",
  "home",
  "laundry",
  "household",
  "cosmetic",
  "medical",
  "education",
  "other",
  "salary",
  "wallet",
  "bonus",
  "freelance",
  "investment",

  // Additional icons (Lucide names)
  "Coffee",
  "Pizza",
  "Apple",
  "Cake",
  "GlassWater",
  "Bus",
  "Plane",
  "Train",
  "Bike",
  "Car",
  "Fuel",
  "ShoppingBag",
  "ShoppingCart",
  "Sparkles",
  "Home",
  "Flame",
  "Droplet",
  "Bolt",
  "Wifi",
  "DollarSign",
  "Coins",
  "HandCoins",
  "TrendingUp",
  "Briefcase",
  "Dumbbell",
  "Pill",
  "Stethoscope",
  "Gamepad2",
  "Film",
  "Music",
  "BookOpen",
  "Tv",
  "Baby",
  "Users",
  "Heart",
  "Wrench",
  "Settings",
  "Phone",
  "Shield",
  "FileText",
  "Mail",
  // Newly added icons
  "CreditCard",
  "Receipt",
  "Store",
  "Ticket",
  "Wine",
  "Hotel",
  "MapPin",
  "Dog",
  "Cat",
  "Hammer",
  "Scissors",
  "Key",
  "Trash2",
  "Sun",
  "Umbrella",
  "Activity",
  "Brain",
  "Bed",
  "Crown",
  "Trophy",
  "Award",
  "HeartHandshake",
  "Calculator",
  // Newly added icons for expanded selection
  "Soup",
  "Beer",
  "IceCream",
  "Fish",
  "Egg",
  "Croissant",
  "Popcorn",
  "Cookie",
  "Map",
  "Globe",
  "Compass",
  "Landmark",
  "Luggage",
  "Tent",
  "Mountain",
  "Anchor",
  "Ship",
  "Sofa",
  "Lightbulb",
  "Plug",
  "Bath",
  "Brush",
  "Laptop",
  "Tablet",
  "Mouse",
  "Printer",
  "Banknote",
  "Percent",
  "CirclePercent",
  "Presentation",
  "ShieldCheck",
  "Hospital",
  "Ambulance",
  "Footprints",
  "Eye",
  "Syringe",
  "Book",
  "Bookmark",
  "PenTool",
  "Palette",
  "Mic",
  "Headphones",
  "Camera",
  "Clapperboard",
  "Target",
  "PawPrint",
  "TreePine",
  "Flower2",
  "Leaf",
  "Bell",
  "Calendar",
  "Clock",
  "Star",
  "Cloud",
  "Moon",
];

// Complete mapping of all icon strings to Lucide Components for general fallback
export const allCategoryIcons: Record<string, LucideIcon> = {
  // Legacy system values (Expenses fallbacks)
  food: Utensils,
  snack: CakeSlice,
  drink: CupSoda,
  phone: Smartphone,
  transport: CarFront,
  personal: CircleUserRound,
  home: House,
  laundry: Shirt,
  household: HousePlus,
  cosmetic: SmilePlus,
  medical: HeartPulse,
  education: GraduationCap,
  other: CircleQuestionMark,
  salary: Wallet,
  wallet: PiggyBank,
  bonus: Gift,
  freelance: ChartPie,
  investment: Bitcoin,

  // Lucide icon names (direct map)
  Utensils,
  Coffee,
  Pizza,
  Apple,
  Cake,
  GlassWater,
  Car,
  Bus,
  Plane,
  Train,
  Bike,
  Fuel,
  ShoppingBag,
  ShoppingCart,
  Gift,
  Shirt,
  Sparkles,
  Home,
  Flame,
  Droplet,
  Bolt,
  Wifi,
  DollarSign,
  TrendingUp,
  Wallet,
  Coins,
  HandCoins,
  Briefcase,
  HeartPulse,
  Dumbbell,
  Pill,
  Pills: Pill, // Alias support for previous "Pills" naming
  Stethoscope,
  Gamepad2,
  Film,
  Music,
  BookOpen,
  Tv,
  GraduationCap,
  Baby,
  Users,
  Heart,
  Wrench,
  Settings,
  Phone,
  Shield,
  FileText,
  Mail,
  // Newly added icons mapping
  CreditCard,
  Receipt,
  Store,
  Ticket,
  Wine,
  Hotel,
  MapPin,
  Dog,
  Cat,
  Hammer,
  Scissors,
  Key,
  Trash2,
  Sun,
  Umbrella,
  Activity,
  Brain,
  Bed,
  Crown,
  Trophy,
  Award,
  HeartHandshake,
  Calculator,
  // Newly added icons mapping
  Soup,
  Beer,
  IceCream,
  Fish,
  Egg,
  Croissant,
  Popcorn,
  Cookie,
  Map,
  Globe,
  Compass,
  Landmark,
  Luggage,
  Tent,
  Mountain,
  Anchor,
  Ship,
  Sofa,
  Lightbulb,
  Plug,
  Bath,
  Brush,
  Laptop,
  Tablet,
  Mouse,
  Printer,
  Banknote,
  Percent,
  CirclePercent,
  Presentation,
  ShieldCheck,
  Hospital,
  Ambulance,
  Footprints,
  Eye,
  Syringe,
  Book,
  Bookmark,
  PenTool,
  Palette,
  Mic,
  Headphones,
  Camera,
  Clapperboard,
  Target,
  PawPrint,
  TreePine,
  Flower2,
  Leaf,
  Bell,
  Calendar,
  Clock,
  Star,
  Cloud,
  Moon,
};

// Helper function to resolve icon key to Lucide Component
export function getCategoryIcon(iconName?: string, type?: string): LucideIcon {
  // ponytail: Removed transaction type checks so that identical iconNames resolve to the same icon component across types, avoiding UI alignment inconsistencies.
  if (!iconName) return CircleQuestionMark;

  return allCategoryIcons[iconName] || CircleQuestionMark;
}
